services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - mongo-prod-data:/data/db

volumes:
  mongo-prod-data:
